## DataSourceConfig
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myspringdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: '000910'

## MybatisConfig
mybatis:
  type-aliases-package: cn.shishc.domain
  mapper-locations: classpath:mapper/*.xml
